import random as r

def guess_number(x):

    print("==========================")
    print("  Welcome to the game :)  ")
    print("==========================\n")
    print(f"The goal of the game is guess the number generated by the computer\n")

    random_number = r.randint(1,x)
    
    input_num  = 0
    
    while input_num != random_number:

        input_num = int(input(f"\nEnter a number between 1 and {x}: "))

        if(input_num < random_number):
            print("\nTry Again. The number that you have entered is LOWER than the random number")
        elif (input_num > random_number):
            print("\nTry Again. The number that you have entered is BIGGER than the random number")
    print("\nCongrats, you guessed the number!\n")


guess_number(50)